name: Electron-Test
on:
  - push
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          ls env:
          cp -r ./.electron ./electron
          cp -r ./css ./electron
          cp -r ./js ./electron
          cp -r ./layui ./electron
          cp ./index.html ./electron
          cp ./LICENSE ./electron
          cd electron
          npm i
          ../.bin/sed -i 's|giftdouyucdn.starudream.cn|gift.douyucdn.cn|g' ./js/init.js
          ../.bin/sed -i 's|maxMessage = 200|maxMessage = 2000|g' ./js/init.js
          npm run pack
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: electron
          path: ./electron/build
