name: Electron
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: PrePack
        run: |
          cp -r ./.electron ./electron
          cp -r ./css ./electron
          cp -r ./js ./electron
          cp -r ./layui ./electron
          cp ./index.html ./electron
          cp ./favicon.ico ./electron/icon.ico
          cp ./LICENSE ./electron
          cd electron
          npm i
          (gc -encoding utf8 ./js/init.js).replace('giftdouyucdn.starudream.cn', 'gift.douyucdn.cn') | sc -encoding utf8 ./js/init.js
          (gc -encoding utf8 ./js/init.js).replace('maxMessage = 200', 'maxMessage = 2000') | sc -encoding utf8 ./js/init.js
          (gc -encoding utf8 ./package.json).replace('1.0.0', $env:GITHUB_REF.SubString(11)) | sc -encoding utf8 ./package.json
      - name: Pack
        run: npm run pack --prefix ./electron
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: electron
          path: ./electron/build
